### ISSUE TITLE
Log errors - TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by VDRainer** [eifinger/here_travel_time#13]
## Version of the custom_component
v1.2.0
HA 0.96.0b4, Python 3.7.4 venv on Ubuntu 16.04

## Configuration

```yaml

sensor:
  - platform: here_travel_time
    name: Home to Work
    app_id: !secret here_app_id
    app_code: !secret here_app_code
    origin: "46.78729557,9.87784816"
    destination: "47.808751,9.904310"
    traffic_mode: true
```

## Describe the bug
Log fills with errors every 5 minutes, but it looks like the sensor updates.
![20190717_12:35:37_001](https://user-images.githubusercontent.com/26381449/61369176-d8a51d00-a88f-11e9-978b-37d90ed35803.png)

Not sure, but i think since the updates yesterday?

## Debug log

```text

2019-07-17 12:14:56 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.home_to_work fails
Traceback (most recent call last):
  File "/srv/ha/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/ha/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 380, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassi/.homeassistant/custom_components/here_travel_time/sensor.py", line 215, in update
    self._here_data.update()
  File "/home/homeassi/.homeassistant/custom_components/here_travel_time/sensor.py", line 293, in update
    if not re.fullmatch(pattern, self.origin):
  File "/srv/ha/lib/python3.7/re.py", line 178, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
TypeError: expected string or bytes-like object

```

**Comment by holdestmade** [comment]
Same here, 

v1.2.0
HA 0.95.4, Python 3.7.3 venv on Ubuntu 19.04

```
Wed Jul 17 2019 11:43:47 GMT+0100 (British Summer Time)
Update for sensor.office_to_home fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/here_travel_time/sensor.py", line 215, in update
    self._here_data.update()
  File "/config/custom_components/here_travel_time/sensor.py", line 293, in update
    if not re.fullmatch(pattern, self.origin):
  File "/usr/local/lib/python3.7/re.py", line 178, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
TypeError: expected string or bytes-like object
```

**Comment by VDRainer** [comment]
Looks like defining zones for origin and destination, the errors are gone.
